# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testlinkHelper.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_testlinkHelper(object):
    def setupUi(self, testlinkHelper):
        testlinkHelper.setObjectName("testlinkHelper")
        testlinkHelper.resize(475, 570)
        testlinkHelper.setMinimumSize(QtCore.QSize(475, 570))
        testlinkHelper.setMaximumSize(QtCore.QSize(500, 570))
        self.centralwidget = QtWidgets.QWidget(testlinkHelper)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 451, 141))
        self.groupBox.setObjectName("groupBox")
        self.gen_temp_Button = QtWidgets.QPushButton(self.groupBox)
        self.gen_temp_Button.setGeometry(QtCore.QRect(349, 60, 91, 23))
        self.gen_temp_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.gen_temp_Button.setObjectName("gen_temp_Button")
        self.importButton = QtWidgets.QPushButton(self.groupBox)
        self.importButton.setGeometry(QtCore.QRect(350, 100, 91, 23))
        self.importButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.importButton.setObjectName("importButton")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 421, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.case_path = QtWidgets.QLineEdit(self.layoutWidget)
        self.case_path.setReadOnly(True)
        self.case_path.setObjectName("case_path")
        self.horizontalLayout_2.addWidget(self.case_path)
        self.case_path_Button = QtWidgets.QPushButton(self.layoutWidget)
        self.case_path_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.case_path_Button.setObjectName("case_path_Button")
        self.horizontalLayout_2.addWidget(self.case_path_Button)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(21, 61, 224, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.proj_comBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.proj_comBox.setMinimumSize(QtCore.QSize(150, 0))
        self.proj_comBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.proj_comBox.setObjectName("proj_comBox")
        self.horizontalLayout.addWidget(self.proj_comBox)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 100, 224, 22))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.target_suitComBox = QtWidgets.QComboBox(self.layoutWidget2)
        self.target_suitComBox.setMinimumSize(QtCore.QSize(150, 0))
        self.target_suitComBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.target_suitComBox.setCurrentText("")
        self.target_suitComBox.setObjectName("target_suitComBox")
        self.horizontalLayout_4.addWidget(self.target_suitComBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 160, 451, 361))
        self.groupBox_2.setObjectName("groupBox_2")
        self.infoTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.infoTextEdit.setGeometry(QtCore.QRect(10, 20, 431, 301))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.infoTextEdit.setFont(font)
        self.infoTextEdit.setReadOnly(True)
        self.infoTextEdit.setObjectName("infoTextEdit")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(270, 330, 172, 25))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.clear_info_Button = QtWidgets.QPushButton(self.layoutWidget3)
        self.clear_info_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clear_info_Button.setObjectName("clear_info_Button")
        self.horizontalLayout_3.addWidget(self.clear_info_Button)
        self.save_info_Button = QtWidgets.QPushButton(self.layoutWidget3)
        self.save_info_Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_info_Button.setObjectName("save_info_Button")
        self.horizontalLayout_3.addWidget(self.save_info_Button)
        testlinkHelper.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(testlinkHelper)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 475, 23))
        self.menubar.setObjectName("menubar")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        testlinkHelper.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(testlinkHelper)
        self.statusbar.setObjectName("statusbar")
        testlinkHelper.setStatusBar(self.statusbar)
        self.actionConfig = QtWidgets.QAction(testlinkHelper)
        self.actionConfig.setObjectName("actionConfig")
        self.actionAbout = QtWidgets.QAction(testlinkHelper)
        self.actionAbout.setObjectName("actionAbout")
        self.action_Quit = QtWidgets.QAction(testlinkHelper)
        self.action_Quit.setObjectName("action_Quit")
        self.actionHelp = QtWidgets.QAction(testlinkHelper)
        self.actionHelp.setObjectName("actionHelp")
        self.menuOptions.addAction(self.actionConfig)
        self.menuOptions.addAction(self.action_Quit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(testlinkHelper)
        self.target_suitComBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(testlinkHelper)

    def retranslateUi(self, testlinkHelper):
        _translate = QtCore.QCoreApplication.translate
        testlinkHelper.setWindowTitle(_translate("testlinkHelper", "TestLink Helper"))
        self.groupBox.setTitle(_translate("testlinkHelper", "Settings"))
        self.gen_temp_Button.setToolTip(_translate("testlinkHelper", "click to generate a temlpate file"))
        self.gen_temp_Button.setStatusTip(_translate("testlinkHelper", "generate template"))
        self.gen_temp_Button.setText(_translate("testlinkHelper", "Gen template"))
        self.importButton.setToolTip(_translate("testlinkHelper", "click to start import"))
        self.importButton.setStatusTip(_translate("testlinkHelper", "start import"))
        self.importButton.setText(_translate("testlinkHelper", "Import"))
        self.label.setText(_translate("testlinkHelper", "TestCase   "))
        self.case_path_Button.setText(_translate("testlinkHelper", "Browser"))
        self.label_2.setText(_translate("testlinkHelper", "TestProject"))
        self.label_3.setText(_translate("testlinkHelper", "TargetSuit "))
        self.groupBox_2.setTitle(_translate("testlinkHelper", "Informations"))
        self.clear_info_Button.setStatusTip(_translate("testlinkHelper", "clear logs"))
        self.clear_info_Button.setText(_translate("testlinkHelper", "clear"))
        self.save_info_Button.setToolTip(_translate("testlinkHelper", "save informations into a log file"))
        self.save_info_Button.setStatusTip(_translate("testlinkHelper", "save information"))
        self.save_info_Button.setText(_translate("testlinkHelper", "save"))
        self.menuOptions.setTitle(_translate("testlinkHelper", "Options"))
        self.menuHelp.setTitle(_translate("testlinkHelper", "Help"))
        self.actionConfig.setText(_translate("testlinkHelper", "Config"))
        self.actionAbout.setText(_translate("testlinkHelper", "&About"))
        self.action_Quit.setText(_translate("testlinkHelper", "&Quit"))
        self.action_Quit.setShortcut(_translate("testlinkHelper", "Ctrl+Q"))
        self.actionHelp.setText(_translate("testlinkHelper", "&Help"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    testlinkHelper = QtWidgets.QMainWindow()
    ui = Ui_testlinkHelper()
    ui.setupUi(testlinkHelper)
    testlinkHelper.show()
    sys.exit(app.exec_())

